services:
    database:
        image: pgvector/pgvector:pg17
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: thesis
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
            target: development
        image: server
        container_name: server
        volumes:
            - ./server/:/usr/server/
            - ./server/package.json:/usr/server/package.json
            - ./server/package-lock.json:/usr/server/package-lock.json
            - server:/usr/server/node_modules
            - server-uploads:/usr/server/uploads
        ports:
            - 3000:3000
        networks:
            - postgres
        depends_on:
            - database

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: hailaconsutu558@gmail.com
            PGADMIN_DEFAULT_PASSWORD: Discoveru1@
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - database
        networks:
            - postgres

    face:
        container_name: face
        build:
            context: ./face
            target: builder
        stop_signal: SIGINT
        volumes:
            - ./face/:/usr/face/
        ports:
            - 5000:5000
        networks:
            - postgres

volumes:
    server:
    server-uploads:
    pgdata:
    pgadmin-data:

networks:
    postgres:
        driver: bridge
