services:
    database:
        image: pgvector/pgvector:pg17
        container_name: thesis-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: thesis
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - postgres

    # server-dev:
    #     container_name: thesis-server
    #     build:
    #         context: ./server
    #         dockerfile: Dockerfile
    #         target: development
    #     volumes:
    #         - ./server/:/usr/server/
    #         - ./server/package.json:/usr/server/package.json
    #         - ./server/package-lock.json:/usr/server/package-lock.json
    #         - server:/usr/server/node_modules
    #         - server-uploads:/usr/server/uploads
    #     ports:
    #         - 3000:3000
    #     networks:
    #         - postgres
    #     depends_on:
    #         - database

    server:
        container_name: thesis-server
        build:
            context: ./server
            dockerfile: Dockerfile
            target: production
        ports:
            - 3000:3000
        networks:
            - postgres
        depends_on:
            - database

    face:
        container_name: thesis-face
        build:
            context: ./face
            target: dev
        stop_signal: SIGINT
        volumes:
            - ./face/:/usr/face/
        ports:
            - 5000:5000
        networks:
            - postgres

    client:
        container_name: thesis-client
        build:
            context: ./client
            dockerfile: Dockerfile
            target: production
        ports:
            - 80:3000
        networks:
            - postgres

    # client-dev:
    #     container_name: thesis-client-dev
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #         target: dev
    #     volumes:
    #         - ./client/:/app/
    #         - ./client/package.json:/app/package.json
    #         - ./client/package-lock.json:/app/package-lock.json
    #         - client:/app/node_modules
    #     ports:
    #         - 80:3000
    #     environment:
    #         WATCHPACK_POLLING: true
    #     networks:
    #         - postgres

    pgadmin:
        image: dpage/pgadmin4:9.5.0
        container_name: thesis-pgadmin4
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - database
        networks:
            - postgres

volumes:
    client:
    server:
    server-uploads:
    pgdata:
    pgadmin-data:

networks:
    postgres:
        driver: bridge
